/* Generated By:JavaCC: Do not edit this line. SMAPParserConstants.java */
package tod.tools.parsers;

public interface SMAPParserConstants {

  int EOF = 0;
  int SMAP = 1;
  int CR = 2;
  int STAR_STRATUM = 3;
  int STAR_FILE = 4;
  int STAR_LINE = 5;
  int STAR_END = 6;
  int STAR_OTHER = 7;
  int STRING = 8;
  int STRCHAR = 9;
  int NUMBER = 10;
  int NUMCHAR = 11;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\"SMAP\"",
    "<CR>",
    "\"*S\"",
    "\"*F\"",
    "\"*L\"",
    "\"*E\"",
    "<STAR_OTHER>",
    "<STRING>",
    "<STRCHAR>",
    "<NUMBER>",
    "<NUMCHAR>",
    "\" \"",
    "\"+\"",
    "\":\"",
    "\",\"",
    "\"#\"",
  };

}
